services:
  mongo:
    image: mongo:7.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: app
    volumes:
      - mongo_data:/data/db

  user-service:
    build:
      context: .
      dockerfile: ./services/user-service/Dockerfile
    container_name: user-service
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - mongo
    env_file:
      - ./services/user-service/.env

  post-service:
    build:
      context: .
      dockerfile: ./services/post-service/Dockerfile
    container_name: post-service
    restart: always
    ports:
      - "8082:8080"
    depends_on:
      - mongo
    env_file:
      - ./services/post-service/.env

  feed-service:
    build:
      context: .
      dockerfile: ./services/feed-service/Dockerfile
    container_name: feed-service
    restart: always
    ports:
      - "8083:8080"
    depends_on:
      - user-service
      - post-service
    env_file:
      - ./services/feed-service/.env

volumes:
  mongo_data:
