receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  debug:

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]