events {}

http {
    upstream user_service {
        server user-service-1:8080;
        server user-service-2:8080; # backup;
    }

    upstream post_service {
        server post-service-1:8080;
        server post-service-2:8080; # backup;
    }

    upstream feed_service {
        server feed-service-1:8080;
        server feed-service-2:8080; # backup;
    }

    server {
        listen 80;

        location ^~ /auth {
            proxy_pass http://user_service;
        }

        location ~ ^/users/.+/posts {
            proxy_pass http://post_service;
        }

        location ^~ /users {
            proxy_pass http://user_service;
        }

        location ^~ /posts {
            proxy_pass http://post_service;
        }

        location ^~ /feed {
            proxy_pass http://feed_service;
        }

        location / {
            return 404;
        }
    }
}