name: CI/CD

on:
  push:
    branches:
      - main

jobs:

  # 🔧 ПЛАН 1: билд + тесты
  build:
    runs-on: ubuntu-latest
    container:
      image: golang:1.25.6-alpine

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install git (required for go mod)
        run: apk add --no-cache git

      - name: Install dependencies
        run: go mod download
      
      - name: Run tests
        run: go test ./...

      - name: Build user-service
        run: go build -o user-service ./services/user-service/cmd/main.go

      - name: Upload artifact (user)
        uses: actions/upload-artifact@v4
        with:
          name: user-service
          path: user-service

      - name: Build post-service
        run: go build -o post-service ./services/post-service/cmd/main.go

      - name: Upload artifact (post)
        uses: actions/upload-artifact@v4
        with:
          name: post-service
          path: post-service

      - name: Build feed-service
        run: go build -o feed-service ./services/feed-service/cmd/main.go

      - name: Upload artifact (feed)
        uses: actions/upload-artifact@v4
        with:
          name: feed-service
          path: feed-service

  # 🚀 ПЛАН 2: docker + delivery
  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout config repo
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "USER_SERVICE_URL=${{ vars.USER_SERVICE_URL }}" >> .env
          echo "POST_SERVICE_URL=${{ vars.POST_SERVICE_URL }}" >> .env
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
          echo "MONGO_DB=${{ secrets.MONGO_DB }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "POST_MONGO_COLLECTION_NAME=${{ secrets.POST_MONGO_COLLECTION_NAME }}" >> .env
          echo "USER_MONGO_COLLECTION_NAME=${{ secrets.USER_MONGO_COLLECTION_NAME }}" >> .env

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # User service
      - name: Download artifact (user)
        uses: actions/download-artifact@v4
        with:
          name: user-service
          path: ./services/user-service/

      - name: Build user image
        run: |
          docker build -t ${{ vars.DOCKER_USERNAME }}/user-service:latest ./services/user-service

      - name: Push user image
        run: docker push ${{ vars.DOCKER_USERNAME }}/user-service:latest

      # Post service
      - name: Download artifact (post)
        uses: actions/download-artifact@v4
        with:
          name: post-service
          path: ./services/post-service/

      - name: Build post image
        run: |
          docker build -t ${{ vars.DOCKER_USERNAME }}/post-service:latest ./services/post-service

      - name: Push post image
        run: docker push ${{ vars.DOCKER_USERNAME }}/post-service:latest

      # Feed service
      - name: Download artifact (feed)
        uses: actions/download-artifact@v4
        with:
          name: feed-service
          path: ./services/feed-service/

      - name: Build feed image
        run: |
          docker build -t ${{ vars.DOCKER_USERNAME }}/feed-service:latest ./services/feed-service

      - name: Push feed image
        run: docker push ${{ vars.DOCKER_USERNAME }}/feed-service:latest
        